---

- hosts: all

  tasks:
  # - name: upgrade all packages
  #   yum: name=* state=latest update_cache=yes
  #   become: true

  - name: install required packages
    yum: name=git,net-tools,zip,unzip,wget state=latest update_cache=yes
    become: true

  - name: install jdk
    yum: name=java-1.8.0-openjdk-devel state=latest update_cache=yes
    become: true

  - name: Adding the path in the bashrc files
    lineinfile:
        dest=/home/vagrant/.bashrc
        line='JAVA_HOME=/etc/alternatives/java_sdk_1.8.0_openjdk'
        insertafter='EOF'
        state=present
    become: true

  - name: Source the bashrc file
    shell: source /home/vagrant/.bashrc

  - name: turn off firewall
    shell:
      systemctl mask firewalld
      systemctl stop firewalld
    become: true

  - name: Disable SElinux
    selinux: state=disabled
    become: true
